spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      settings:
        web-allow-others: ${SPRING_H2_CONSOLE_SETTINGS_WEB-ALLOW-OTHERS}
      enabled: ${SPRING_H2_CONSOLE_ENABLED}
      path: /h2-console
  jackson:
    mapper:
      allow-coercion-of-scalars: true
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true

#Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#Swagger
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api/v1/pet/trackers/v3/api/docs
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    path: /api/v1/pet/trackers/swagger-ui